### ISSUE TITLE
how to declare swapExactToken function?

### ISSUE THREAD

**Issue by montedev0516** [montedev0516/MonoX-finance-platform#2]

**Comment by tosky19941209** [comment]
function swapExactTokenForToken(
    address tokenIn,
    address tokenOut,
    uint amountIn,
    uint amountOutMin,
    address to,
    uint deadline
  ) external override virtual ensure(deadline) returns (uint amountOut) {
    amountOut = IMonoswap(core).swapIn(tokenIn, tokenOut, msg.sender, to, amountIn);
    require(amountOut >= amountOutMin, 'MonoswapRouter:INSUFF_OUTPUT');
  }

**Comment by montedev0516** [comment]
okay
