### ISSUE TITLE
swapETHForExactToken?

### ISSUE THREAD

**Issue by montedev0516** [montedev0516/MonoX-finance-platform#4]
swapETHForExactToken function!

**Comment by montedev0516** [comment]
function swapETHForExactToken(
    address tokenOut,
    uint amountInMax,
    uint amountOut,
    address to,
    uint deadline
  ) external override virtual payable ensure(deadline) returns (uint amountIn) {
    uint amountSentIn = msg.value;
    ( , , amountIn, ) = IMonoswap(core).getAmountIn(WETH, tokenOut, amountOut);
    MonoXLibrary.safeTransferETH(monoXPool, amountIn);
    IMonoXPool(monoXPool).depositWETH(amountIn);
    amountIn = IMonoswap(core).swapOut(WETH, tokenOut, core, to, amountOut);
    require(amountIn <= amountSentIn, 'MonoX:BAD_INPUT');
    require(amountIn <= amountInMax, 'MonoX:EXCESSIVE_INPUT');
    if (amountSentIn > amountIn) {
      MonoXLibrary.safeTransferETH(msg.sender, amountSentIn.sub(amountIn));
    }
  }

**Comment by driveForward0516** [comment]
Great!
